name: Upload websit to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@master
      uses: jakejarvis/s3-sync-action@master
    with:
      args: --acl public-read --folllow-symlinks --delete
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACESS_KEY_ID: ${{ secrets.AWS_ACESS_KEY_ID }}
      AWS_SECRET_ACESS_KEY: ${{ secrets.AWS_SECRET_ACESS_KEY }}
      AWS_REGION: 'us-east-1'
      SOURCE_DIR: 'site'